/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';

import { useGLTF, useAnimations } from '@react-three/drei';

///import { Stats, OrbitControls, Environment, useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./models/roan.glb');
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Yearling_hourse">
          <group name="Geometry">
            <skinnedMesh
              name="yearling_tail"
              geometry={nodes.yearling_tail.geometry}
              material={materials.StingrayPBS1}
              skeleton={nodes.yearling_tail.skeleton}
            />
            <skinnedMesh
              name="Thoroughbred_yearling"
              geometry={nodes.Thoroughbred_yearling.geometry}
              material={materials.StingrayPBS1}
              skeleton={nodes.Thoroughbred_yearling.skeleton}
            />
            <skinnedMesh
              name="Yearling_mane"
              geometry={nodes.Yearling_mane.geometry}
              material={materials.StingrayPBS1}
              skeleton={nodes.Yearling_mane.skeleton}
            />
          </group>
        </group>
        <primitive object={nodes.root} />
      </group>
    </group>
  );
}

useGLTF.preload('./models/roan.glb');
